### PR TITLE
Added binary search and ability to drop ellipsis char

### LINKED ISSUE #10: Totally freezes the tab
As soon as I enter a component with `snEllipsis` the application freezes.
The Chrome task manager CPU raises over 130.

Env:
- Asus ROG 2015 (i7 6700 HQ + GTX960M + 16GB RAM DDR4)
- Chrome 65.0.3325.181 x64

<pre><code>
@angular/cdk: 5.2.4
@angular/cli: 1.6.3
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.4.8
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0**
</code></pre>

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #10.

### CODE REVIEW

**Comment by krak3n** [comment]
HI @andrew-aladev thanks for your PR :+1: @edoparearyee is currently on Holiday for a couple of weeks (I'm not a FE dev and have no idea what this does :smile:) So might take a little while for this to get reviewed.

**Comment by andrew-aladev** [comment]
It it is possible for us to split the last word into characters, mechanism of adding ellipsis char will be different.You can add per-character strategy by modifying the second block.

**Comment by edoparearyee** [comment]
As mentioned [here](https://github.com/thisissoon/angular-ellipsis/issues/10#issuecomment-405189342) I am unable to reproduce the issue. Once I have a code sample to test against will look to merge this in.

**Comment by edoparearyee** [comment]
Closing as this has been superseded by #12

**Pull request closed without merging**
